nusFinTech/nusFinTech/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from services import views
urlpatterns = [
    path('', views.index, name='index'),
    path('services/', include('services.urls')),
    path('admin/', admin.site.urls),
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('user_consent', views.user_consent, name='user_consent'),
]

nusFinTech/services/urls.py
from django.contrib import admin
from django.urls import path
from services import views
from services.models import ETF, ETFHistory, Account, AccountTransaction, AccountSummary
from datetime import datetime, timedelta
import random

import logging
logger = logging.getLogger('urls')

app_name = 'services'
urlpatterns = [
    path('', views.index, name='index'),
	path('portfolio_composition', views.portfolioComposition, name='portfolio_composition'),
	path('account_setting', views.accountSetting, name='account_setting'),
    path('submit_score', views.submit_score, name='submit_score'),
    path('makeTransaction', views.makeTransaction, name='makeTransaction'),
    path('withdraw', views.withdraw, name='withdraw'),
    path('timeSeriesAUM', views.timeSeriesAUM, name='timeSeriesAUM'),
    path('transactionHistory', views.transactionHistory, name='transactionHistory'),
    path('report', views.report, name='report'),
    path('monthlyReport', views.monthlyReport, name='monthlyReport'),
    path('yearlyReport', views.yearlyReport, name='yearlyReport'),
]

def updateETFHistory(nForward=0):
    logger.info('updating etf history from last update to today...')
    etfs = ETF.objects.all()
    aum = [ {'eq': 0.2, 'fi': 0.2, 'co': 0.2, 'ca': 0.4}, 
            {'eq': 0.3, 'fi': 0.2, 'co': 0.3, 'ca': 0.2}, 
            {'eq': 0.4, 'fi': 0.1, 'co': 0.4, 'ca': 0.1}]
    riskLevel = 0

    for etf in etfs:
        etf_history = etf.history.order_by('-date').first()
        if etf_history is None:
            continue
        logger.info(etf_history)
        today_date = datetime.now().date()
        day_diff = today_date - etf_history.date
        logger.info('{0} days since last patch to ETF History!'.format(day_diff.days))
        if day_diff.days > 1:
            for aDate in (etf_history.date + timedelta(days=n) for n in range(1, day_diff.days+nForward)):
                delta = (riskLevel + 1) * random.randint(20, 40)/10000
                eq_pct = etf_history.equity_pct + random.randint(-40, 40)/10000
                fi_pct = etf_history.fixed_income_pct + random.randint(-40, 40)/10000
                co_pct = etf_history.commodities_pct + random.randint(-40, 40)/10000
                ca_pct = 1 - (eq_pct + fi_pct + co_pct)
                ETFHistory.objects.get_or_create(etf=etf, date=aDate, delta=delta, equity_pct = eq_pct, 
                                                fixed_income_pct = fi_pct, commodities_pct = co_pct, cash_pct = ca_pct)
        riskLevel += 1
        


def updateTransactionProfit(nForward=0):
    logger.info('updating Transaction Profit history from last update to yesterday...')
    accounts = Account.objects.all()
    for account in accounts:
        etfHistory = account.selectedETF.history.order_by('date')
        profit_txns = list(filter(lambda txn: txn.type == AccountTransaction.TYPERETURN or txn.type == AccountTransaction.TYPELOSS, account.transactions.order_by('dateTime')))
        if len(profit_txns) <= 0:
            continue
        
        lastProfitDate = profit_txns[-1].dateTime.date()
        today_date = datetime.today().date()

        day_diff = today_date - lastProfitDate
        logger.info('{0} days since last patch to Account Profits'.format(str(day_diff.days)))
        if day_diff.days > 1:
            for aDate in (lastProfitDate + timedelta(days=n) for n in range(1, day_diff.days+nForward)):
                account_summary = AccountSummary(account)
                that_day_txns = list(filter(lambda txn: txn.transactionDate == aDate, account_summary.transactionLedger))
                that_day_etf_history = list(filter(lambda etfh: etfh.date == aDate, etfHistory))
                
                balance = account_summary.transactionLedger[-1].balance
                if len(that_day_txns) != 0:
                    balance = that_day_txns[0].balance
                
                delta = etfHistory.last().delta
                if len(that_day_etf_history) != 0:
                    delta = that_day_etf_history[0].delta
                
                profit = balance * delta

                type = AccountTransaction.TYPERETURN if profit > 0 else AccountTransaction.TYPELOSS
                AccountTransaction.objects.get_or_create(account=account, amount=profit, dateTime=aDate, type=type)

updateETFHistory()

updateTransactionProfit()

nusFinTech/services/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

import logging
logger = logging.getLogger('models')

# Create your models here.
class ETF(models.Model):
    id = models.IntegerField(primary_key=True, auto_created=True, editable=False)
    name = models.CharField(max_length=50)

    def __str__(self):
        return "{0} {1}".format(str(self.id), self.name)

class ETFHistory(models.Model):
    etf = models.ForeignKey(ETF, on_delete=models.CASCADE, related_name='history')
    date = models.DateField()
    delta = models.FloatField()
    equity_pct = models.FloatField()
    fixed_income_pct = models.FloatField()
    commodities_pct = models.FloatField()
    cash_pct = models.FloatField()

    def __str__(self):
        return "{0} {1} {2:0.3f} Eq: {3:0.3f} Fi: {4:0.3f} Co: {5:0.3f} Ca: {6:0.3f}".format(self.etf.name, str(self.date), self.delta, self.equity_pct, self.fixed_income_pct, self.commodities_pct, self.cash_pct)

class ETFMonthlySummary(models.Model):
    etf = models.ForeignKey(ETF, on_delete=models.CASCADE, related_name='monthly')
    date = models.DateField()
    delta = models.FloatField()
    equity_pct = models.FloatField()
    fixed_income_pct = models.FloatField()
    commodities_pct = models.FloatField()
    cash_pct = models.FloatField()
    def __str__(self):
        return "{0} {1} {2:0.3f} Eq: {3:0.3f} Fi: {4:0.3f} Co: {5:0.3f} Ca: {6:0.3f}".format(self.etf.name, str(self.date), self.delta, self.equity_pct, self.fixed_income_pct, self.commodities_pct, self.cash_pct)

class ETFYearlySummary(models.Model):
    etf = models.ForeignKey(ETF, on_delete=models.CASCADE, related_name='yearly')
    date = models.DateField()
    delta = models.FloatField()
    equity_pct = models.FloatField()
    fixed_income_pct = models.FloatField()
    commodities_pct = models.FloatField()
    cash_pct = models.FloatField()
    def __str__(self):
        return "{0} {1} {2:0.3f} Eq: {3:0.3f} Fi: {4:0.3f} Co: {5:0.3f} Ca: {6:0.3f}".format(self.etf.name, str(self.date), self.delta, self.equity_pct, self.fixed_income_pct, self.commodities_pct, self.cash_pct)


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    id = models.IntegerField(primary_key=True, auto_created=True, editable=False)
    name = models.CharField(max_length=250)
    mobileNo = models.CharField(max_length=10)
    selectedETF = models.ForeignKey(ETF, on_delete=models.DO_NOTHING,blank=True, null=True)
    consentGiven = models.BooleanField(default=False)

    def __str__(self):
        return "{0} {1} {2}".format(self.user.username, self.name, self.mobileNo)

class AccountTransaction(models.Model):

    TYPEDEPOSIT = 'D'
    TYPEWITHDRAW = 'W'
    TYPERETURN = 'R'
    TYPELOSS = 'L'

    TYPE_CHOICES = [(TYPEDEPOSIT, 'Deposit'), (TYPEWITHDRAW, 'Withdraw'), (TYPERETURN, 'Return'), (TYPELOSS, 'Loss')]

    id = models.IntegerField(primary_key=True, auto_created=True, editable=False)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='transactions')
    amount = models.FloatField()
    dateTime = models.DateTimeField(auto_now_add=False)
    type = models.CharField(max_length=1, choices=TYPE_CHOICES, default=TYPEDEPOSIT)
    
    def __str__(self):
        return "{0} {1} {2} {3} {4}".format(str(self.id), self.account, str(self.amount), self.type, str(self.dateTime))

class MonthlySummary(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='monthly_summary')
    closing_balance = models.FloatField()
    profit = models.FloatField()
    month_year_date = models.DateTimeField()
    
    def __str__(self):
        return "{0} {1} {2} {3}".format(self.account.name, str(self.closing_balance), str(self.profit), self.month_year_date.strftime("%m/%Y"))

class YearlySummary(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='yearly_summary')
    closing_balance = models.FloatField()
    profit = models.FloatField()
    year_date = models.DateTimeField()

    def __str__(self):
        return "{0} {1} {2} {3}".format(self.account.name, str(self.closing_balance), str(self.profit), self.year_date.strftime("%Y"))

class TransactionPrice():
    def __init__(self, accountTransaction, previousBalance):
        self.transactionDate = accountTransaction.dateTime.date()
        self.amount = accountTransaction.amount
        self.profit = 0
        if (accountTransaction.type == AccountTransaction.TYPEWITHDRAW or
            accountTransaction.type == AccountTransaction.TYPELOSS):
            self.amount *= -1

        if accountTransaction.type == AccountTransaction.TYPELOSS:
            self.profit = -1.0 * accountTransaction.amount
        elif accountTransaction.type == AccountTransaction.TYPERETURN:
            self.profit = accountTransaction.amount
        

        self.balance = previousBalance + self.amount

    def add(self, accountTransaction):
        addAmount = accountTransaction.amount
        if (accountTransaction.type == AccountTransaction.TYPEWITHDRAW or
            accountTransaction.type == AccountTransaction.TYPELOSS):
            addAmount *= -1

        if accountTransaction.type == AccountTransaction.TYPELOSS:
            self.profit = -1.0 * accountTransaction.amount
        elif accountTransaction.type == AccountTransaction.TYPERETURN:
            self.profit = accountTransaction.amount

        self.balance += addAmount



    def __str__(self):
        return "{0} {1} {2} {3}".format(self.transactionDate.strftime("%Y/%m/%d %H:%M:%S"), str(self.amount), str(self.balance), str(self.profit))

class AccountSummary():
    def __init__(self, account):
        transactions = AccountTransaction.objects.filter(account=account).order_by('dateTime')
        today = datetime.now().date()
        self.last_balance = 0
        self.last_profit = 0

        self.transactionLedger = []
        balance = 0
        logger.info('total no of transactions {0}'.format(str(len(transactions))))
        for trxn in transactions:
            foundSameDateTrxn = False
            for transactionPrice in self.transactionLedger:
                if (transactionPrice.transactionDate == trxn.dateTime.date()):
                    transactionPrice.add(trxn)
                    balance = transactionPrice.balance
                    foundSameDateTrxn = True
                    break
                
            if not foundSameDateTrxn:
                transactionPrice = TransactionPrice(trxn, balance)
                balance = transactionPrice.balance
                self.transactionLedger.append(transactionPrice)

        if len(self.transactionLedger) > 0:
            
            self.last_balance = self.transactionLedger[-1].balance

            if self.transactionLedger[-1].transactionDate == today:
                if len(self.transactionLedger) > 1:
                    self.last_profit = self.transactionLedger[-2].profit
                else:
                    self.last_profit = 0
            else:
                self.last_profit = self.transactionLedger[-1].profit

nusFinTech/services/forms.py
from django import forms
from django.contrib.auth.models import User
from services.models import Account, AccountTransaction

class AccountTransactionForm(forms.ModelForm):
    class Meta():
        model = AccountTransaction
        fields = ['amount',]

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ['username', 'email', 'password',]

class AccountForm(forms.ModelForm):
    class Meta():
        model = Account
        fields = ['name', 'mobileNo',]

class AccountETFForm(forms.ModelForm):
    class Meta():
        model = Account
        fields = ['selectedETF',]

nusFinTech/templates/services/accountSetting.html
{% extends "base.html" %}
    {% block body_block %}
    {% if transaction_performed %}
	        <div class="toast" data-delay="2000" style="position: absolute; top: 35%; right: 0;">
              <div class="toast-header">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg>
                {% if success_message|length > 0 %}
                <strong class="mr-auto text-success">Success</strong>
                {% else %}
                <strong class="mr-auto text-danger">Failure</strong>
                {% endif%}
                <small>just now</small>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="toast-body">
                
                {% if success_message|length > 0 %}
                {{ success_message }}
                {% else %}
                {{ error_message }}
                {% endif %}
              </div>
            </div>
  {% endif %}
  <br>
    <h3>Your current investment option is: <strong>{{ account.selectedETF.name }}</strong></h3>
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" name="submit" value="Submit"/> 
    </form>
    {% endblock %}

    {% block js_block %}
    {% if transaction_performed %}
    <script>
    $('.toast').toast('show')
    </script>
    {% endif %}
    {% endblock %}

nusFinTech/templates/services/makeTransaction.html
{% extends "base.html" %}
    {% block body_block %}
	{% if transactionPerformed %}
	      <div class="toast" data-delay="2000" style="position: absolute; top: 35%; right: 0;">
            <div class="toast-header">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg>
              {% if noError %}
              <strong class="mr-auto text-success">Success</strong>
              {% else %}
              <strong class="mr-auto text-danger">Failure</strong>
              {% endif %}
              <small>just now</small>
              <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="toast-body">
              {{ postMessage }}
            </div>
          </div>
  {% endif %}
  <br>
	<h3>Please input the amount to deposit: </h3>
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" name="submit" value="Submit"/> 
    </form>
    {% endblock %}

    
    {% block js_block %}
    {% if transactionPerformed %}
    <script>
    $('.toast').toast('show')
    </script>
    {% endif %}
    {% endblock %}

nusFinTech/templates/services/monthlyReport.html
{% extends "base.html" %}
    {% block body_block %}
        <canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="1076" height="454"
            style="display: block; width: 1076px; height: 454px;"></canvas>

        <h2>Monthly Accumulation</h2>
        <div class="float-left w-50">
        {% for trxn in ledger reversed %}
        <div class="container border-bottom border-dark">
            <div class="row justify-content-md-left">
                <div class="col col-lg-2 font-weight-bold">Return</div>
                {% if trxn.profit > 0 %}
                <div class="col col-lg-2 font-weight-bold text-success">
                {% else %}
                <div class="col col-lg-2 font-weight-bold text-danger">
                {% endif %}
                    {{trxn.profit|floatformat:3}}
                </div>
            </div>
            <div class="row justify-content-md-left">
                <div class="col col-lg-2 font-weight-light">{{trxn.month_year_date|date:"m/Y"}}</div>
                <div class="col col-lg-2 font-weight-light">{{trxn.closing_balance|floatformat:3}}</div>    
            </div>
        </div>
        {% endfor %}
        </div>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
        
        <script>
            /* globals Chart:false, feather:false */

            (function () {
                'use strict'

                feather.replace()

                // Graphs
                var ctx = document.getElementById('myChart')
                // eslint-disable-next-line no-unused-vars
                var myChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: [
                        {% for trxn in ledger %}
                            '{{trxn.month_year_date|date:"m/Y"}}',
                        {% endfor %}
                        ],
                        datasets: [{
                            label: 'Balance',
                            backgroundColor: '#36a2eb',
                            stack: 'Stack 0',
                            data: [
                            {% for trxn in ledger %}
                            {{trxn.closing_balance|floatformat:3}},
                            {% endfor %}
                            ]
                        },
                        {
                            label: 'Return',
                            backgroundColor: '#ff6384',
                            stack: 'Stack 0',
                            data: [    
                            {% for trxn in ledger %}
                            {{trxn.profit|floatformat:3}},
                            {% endfor %}
                            ]
                        }
                        ]
                    },
                    options: {
                        title: {
                            display: true,
                            text: 'Monthly Accumulation'
                        },
                        tooltips: {
                            mode: 'index',
                            intersect: 'false'
                        },
                        responsives: true,
                        scales: {
                            xAxes: [{
                                stacked: true
                            }],
                            yAxes: [{
                                stacked: true
                            }]
                        }
                    }
                })

                ctx.onclick = function(e) {
                    var slice = myChart.getElementAtEvent(e);
                    if (!slice.length) return;

                    var label = slice[0]._model.label;
                    window.location = "{% url 'services:report' %}?period="+label
                }
            }())

        </script>
    {% endblock%}

nusFinTech/templates/services/portfolioComposition.html
{% extends "base.html" %}
    {% block body_block %}
    <h1>This page will describe the Portfolio Composition</h1>
	<h2>It will describe about the investment made (Equity, Fixed Income, Commodities, Cash)</h2>
	{% endblock %}

nusFinTech/templates/services/report.html
{% extends "base.html" %}
    {% block body_block %}
        <canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="1076" height="454"
            style="display: block; width: 1076px; height: 454px;"></canvas>

        <div class="container border border-dark rounded">
            <div class="row justify-content-md-center">
                <div class="col col-lg-2"><small>Balance</small></div>
                <div class="col col-lg-2"><small>Return</small></div>
            </div>
            <div class="row justify-content-md-center">
                <div class="col col-lg-2"><h2>{{ summary.last_balance|floatformat:3 }}</h2></div>
                <div class="col col-lg-2">
                {% if summary.last_profit > 0 %}
                    <h2 class="text-success">{{ summary.last_profit|floatformat:3 }}</h2>
                {% else %}
                    <h2 class="text-danger">{{ summary.last_profit|floatformat:3 }}</h2>
                {% endif %}
                </div>
            </div>

        </div>
        <h2>{{ title }}</h2>
        <div class="float-left w-50">
        {% for trxn in summary.transactionLedger reversed %}
        <div class="container border-bottom border-dark">
            <div class="row justify-content-md-left">
                <div class="col col-lg-2 font-weight-bold">Return</div>
                {% if trxn.profit > 0 %}
                <div class="col col-lg-2 font-weight-bold text-success">
                {% else %}
                <div class="col col-lg-2 font-weight-bold text-danger">
                {% endif %}
                    {{trxn.profit|floatformat:3}}
                </div>
            </div>
            <div class="row justify-content-md-left">
                <div class="col col-lg-2 font-weight-light">{{trxn.transactionDate|date:"d/m/Y"}}</div>
                <div class="col col-lg-2 font-weight-light">{{trxn.balance|floatformat:3}}</div>    
            </div>
        </div>
        {% endfor %}
        </div>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
        
        <script>
            /* globals Chart:false, feather:false */

            (function () {
                'use strict'

                feather.replace()

                // Graphs
                var ctx = document.getElementById('myChart')
                // eslint-disable-next-line no-unused-vars
                var myChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: [
                        {% for trxn in summary.transactionLedger %}
                            '{{trxn.transactionDate|date:"d/m/Y"}}',
                        {% endfor %}
                        ],
                        datasets: [{
                            label: 'Balance',
                            backgroundColor: '#36a2eb',
                            stack: 'Stack 0',
                            data: [
                            {% for trxn in summary.transactionLedger %}
                            {{trxn.balance|floatformat:3}},
                            {% endfor %}
                            ]
                        },
                        {
                            label: 'Return',
                            backgroundColor: '#ff6384',
                            stack: 'Stack 0',
                            data: [    
                            {% for trxn in summary.transactionLedger %}
                            {{trxn.profit|floatformat:3}},
                            {% endfor %}
                            ]
                        }
                        ]
                    },
                    options: {
                        title: {
                            display: true,
                            text: '{{ title }}'
                        },
                        tooltips: {
                            mode: 'index',
                            intersect: 'false'
                        },
                        responsives: true,
                        scales: {
                            xAxes: [{
                                stacked: true
                            }],
                            yAxes: [{
                                stacked: true
                            }]
                        }
                    }
                })
            }())

        </script>
    {% endblock%}

nusFinTech/templates/services/survey.html
{% extends "base.html" %}
    {% load staticfiles %}
    {% block body_block %}
    <script src="https://unpkg.com/jquery"></script>
    <script src="https://surveyjs.azureedge.net/1.1.16/survey.jquery.js"></script>
    <link href="https://surveyjs.azureedge.net/1.1.16/survey.css" type="text/css" rel="stylesheet"/>
    <!--link rel="stylesheet" href="./index.css"-->
    <link href="https://surveyjs.azureedge.net/1.1.16/survey.analytics.css" rel="stylesheet"/>

    <script src="https://cdn.rawgit.com/inexorabletash/polyfill/master/typedarray.js"></script>

    <script src="https://polyfill.io/v3/polyfill.min.js"></script>

    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    <script src="https://unpkg.com/wordcloud@1.1.0/src/wordcloud2.js"></script>

    <!--script src="https://surveyjs.azureedge.net/1.1.16/survey.analytics.js"></script-->
    <style>
        table, th, td {
          border: 1px solid black;
        }
    </style>
        <div style="margin: 20px;">
            <h1>Risk Tolerance Survey</h1>
            <!--a href="https://surveyjs.io/Service/SurveyNPS" style="font-size: 24px">You can see analytics immediately. Just click this link</a>

            <p>
                or you can pass the survey and see the embedded analytics
            </p>

            <p>
                The results of this survey are not collected. In case you want to take a real survey please follow the link:
                <a href="https://surveyjs.io/published?id=87b306f1-e41c-47c3-99de-1d2cd46c8253" style="font-size: 24px">NPS Survey</a>
            </p-->
        </div>
        <div id="surveyElement"></div>
        <div id="surveyResult"></div>
        <div id="json-records"></div>

        <script type="text/javascript" src="{% static 'js/survey.js' %}"></script>
        
    {% endblock %}

nusFinTech/templates/services/timeSeriesAUM.html
{% extends "base.html" %}
    {% block body_block %}
        <canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="1076" height="454"
            style="display: block; width: 1076px; height: 454px;"></canvas>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
        
        <script>
            /* globals Chart:false, feather:false */

            (function () {
                'use strict'

                feather.replace()

                // Graphs
                var ctx = document.getElementById('myChart')
                // eslint-disable-next-line no-unused-vars
                var myChart = new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: [
                        {% for h in history %}
                            '{{h.date|date:"d/m/Y"}}',
                        {% endfor %}
                        ],
                        datasets: [{
                            label: 'Price',
                            backgroundColor: '#36a2eb',
                            stack: 'Stack 0',
                            data: [
                            {% for h in history %}
                            {{h.price|floatformat:3}},
                            {% endfor %}
                            ],
                            lineTension: 0,
                            backgroundColor: 'transparent',
                            borderColor: '#007bff',
                            borderWidth: 4,
                            pointBackgroundColor: '#007bff'
                        }]
                    },
                    options: {
                        title: {
                            display: true,
                            text: 'Time-Series AUM'
                        },
                        tooltips: {
                            mode: 'index',
                            intersect: 'false'
                        },
                        responsives: true,
                        scales: {
                            
                            yAxes: [{
                                ticks: {
                                    beginAtZero: false
                                }
                            }]
                        }
                    }
                })
            }())

        </script>
    {% endblock%}

nusFinTech/templates/services/transactionHistory.html
{% extends "base.html" %}
    {% block body_block %}
    <br>
        <h2>Transaction History</h2>
        <div class="float-left w-50">
        {% for trxn in transactions reversed %}
        <div class="container border-bottom border-dark">
            <div class="row justify-content-md-left">
                <div class="col col-lg-2 font-weight-bold">Amount</div>
                {% if trxn.amount > 0 %}
                <div class="col col-lg-2 font-weight-bold text-success">
                {% else %}
                <div class="col col-lg-2 font-weight-bold text-danger">
                {% endif %}
                    {{trxn.amount|floatformat:3}}
                </div>
            </div>
            <div class="row justify-content-md-left">
                <div class="col col-lg-2 font-weight-light">{{trxn.dateTime|date:"d/m/Y"}}</div>
                <div class="col col-lg-2 font-weight-light">{{trxn.get_type_display}}</div>    
            </div>
        </div>
        {% endfor %}
        </div>
        
    {% endblock%}