nusFinTech/nusFinTech/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from services import views
urlpatterns = [
    path('', views.index, name='index'),
    path('services/', include('services.urls')),
    path('admin/', admin.site.urls),
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
    path('user_logout', views.user_logout, name='user_logout'),
    path('user_consent', views.user_consent, name='user_consent'),
]

nusFinTech/services/urls.py
from django.contrib import admin
from django.urls import path
from services import views
from services.models import ETF, ETFHistory, Account, AccountTransaction, AccountSummary
from datetime import datetime, timedelta
import random

import logging
logger = logging.getLogger('urls')

app_name = 'services'
urlpatterns = [
    path('', views.index, name='index'),
	path('portfolio_composition', views.portfolioComposition, name='portfolio_composition'),
	path('account_setting', views.accountSetting, name='account_setting'),
    path('submit_score', views.submit_score, name='submit_score'),
    path('makeTransaction', views.makeTransaction, name='makeTransaction'),
    path('withdraw', views.withdraw, name='withdraw'),
    path('timeSeriesAUM', views.timeSeriesAUM, name='timeSeriesAUM'),
    path('transactionHistory', views.transactionHistory, name='transactionHistory'),
    path('report', views.report, name='report'),
    path('monthlyReport', views.monthlyReport, name='monthlyReport'),
    path('yearlyReport', views.yearlyReport, name='yearlyReport'),
]

def updateETFHistory(nForward=0):
    logger.info('updating etf history from last update to today...')
    etfs = ETF.objects.all()
    aum = [ {'eq': 0.2, 'fi': 0.2, 'co': 0.2, 'ca': 0.4}, 
            {'eq': 0.3, 'fi': 0.2, 'co': 0.3, 'ca': 0.2}, 
            {'eq': 0.4, 'fi': 0.1, 'co': 0.4, 'ca': 0.1}]
    riskLevel = 0

    for etf in etfs:
        etf_history = etf.history.order_by('-date').first()
        if etf_history is None:
            continue
        logger.info(etf_history)
        today_date = datetime.now().date()
        day_diff = today_date - etf_history.date
        logger.info('{0} days since last patch to ETF History!'.format(day_diff.days))
        if day_diff.days > 1:
            for aDate in (etf_history.date + timedelta(days=n) for n in range(1, day_diff.days+nForward)):
                delta = (riskLevel + 1) * random.randint(20, 40)/10000
                eq_pct = etf_history.equity_pct + random.randint(-40, 40)/10000
                fi_pct = etf_history.fixed_income_pct + random.randint(-40, 40)/10000
                co_pct = etf_history.commodities_pct + random.randint(-40, 40)/10000
                ca_pct = 1 - (eq_pct + fi_pct + co_pct)
                ETFHistory.objects.get_or_create(etf=etf, date=aDate, delta=delta, equity_pct = eq_pct, 
                                                fixed_income_pct = fi_pct, commodities_pct = co_pct, cash_pct = ca_pct)
        riskLevel += 1
        


def updateTransactionProfit(nForward=0):
    logger.info('updating Transaction Profit history from last update to yesterday...')
    accounts = Account.objects.all()
    for account in accounts:
        etfHistory = account.selectedETF.history.order_by('date')
        profit_txns = list(filter(lambda txn: txn.type == AccountTransaction.TYPERETURN or txn.type == AccountTransaction.TYPELOSS, account.transactions.order_by('dateTime')))
        if len(profit_txns) <= 0:
            continue
        
        lastProfitDate = profit_txns[-1].dateTime.date()
        today_date = datetime.today().date()

        day_diff = today_date - lastProfitDate
        logger.info('{0} days since last patch to Account Profits'.format(str(day_diff.days)))
        if day_diff.days > 1:
            for aDate in (lastProfitDate + timedelta(days=n) for n in range(1, day_diff.days+nForward)):
                account_summary = AccountSummary(account)
                that_day_txns = list(filter(lambda txn: txn.transactionDate == aDate, account_summary.transactionLedger))
                that_day_etf_history = list(filter(lambda etfh: etfh.date == aDate, etfHistory))
                
                balance = account_summary.transactionLedger[-1].balance
                if len(that_day_txns) != 0:
                    balance = that_day_txns[0].balance
                
                delta = etfHistory.last().delta
                if len(that_day_etf_history) != 0:
                    delta = that_day_etf_history[0].delta
                
                profit = balance * delta

                type = AccountTransaction.TYPERETURN if profit > 0 else AccountTransaction.TYPELOSS
                AccountTransaction.objects.get_or_create(account=account, amount=profit, dateTime=aDate, type=type)

updateETFHistory()

updateTransactionProfit()

nusFinTech/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<!-- saved from url=(0054)# -->
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v3.8.5">
  <title>DBS SaVest Fund Management System</title>


  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="{% static "css/layout.css" %}" rel="stylesheet">
  <style type="text/css">
    /* Chart.js */
    @-webkit-keyframes chartjs-render-animation {
      from {
        opacity: 0.99
      }

      to {
        opacity: 1
      }
    }

    @keyframes chartjs-render-animation {
      from {
        opacity: 0.99
      }

      to {
        opacity: 1
      }
    }

    .chartjs-render-monitor {
      -webkit-animation: chartjs-render-animation 0.001s;
      animation: chartjs-render-animation 0.001s;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-dark fixed-top bg-danger flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'index'%}">DBS SaVest</a>
	{% if user.is_authenticated %}
	<p class="navbar-text text-white">Welcome, {{ user.get_username }}</p>
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link text-white" href="{% url 'user_logout' %}">Sign out</a>
      </li>
    </ul>
	{% endif %}
  </nav>

  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
            <ul class="nav flex-column">
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'index' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                      stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                      class="feather feather-home">
                      <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                      <polyline points="9 22 9 12 15 12 15 22"></polyline>
                    </svg>
                    Dashboard <span class="sr-only">(current)</span>
                  </a>
                </li>
                <!--li class="nav-item">
                  <a class="nav-link" href="{% url 'services:portfolio_composition' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                      stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                      class="feather feather-layers">
                      <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
                      <polyline points="2 17 12 22 22 17"></polyline>
                      <polyline points="2 12 12 17 22 12"></polyline>
                    </svg>
                    Portfolio Composition
                  </a>
                </li-->
                
                  {% else %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'user_login' %}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                          stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                          class="feather feather-lock">
                          <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
                          <path d="M7 11V7a5 5 0 0 1 10 0v4"></path>
                        </svg>
                        Login
                      </a>
                    </li>
                  {% endif %}
              </ul>
          
          {% if user.is_authenticated %}
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Transaction Operation</span>
            </h6>
          <ul class="nav flex-column mb-2">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'services:account_setting' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-users">
                  <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                  <circle cx="9" cy="7" r="4"></circle>
                  <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                  <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                </svg>
                Account
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'services:makeTransaction' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" 
                  stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-download">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                  <polyline points="7 10 12 15 17 10"></polyline>
                  <line x1="12" y1="15" x2="12" y2="3"></line>
                </svg>
                Deposit
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'services:withdraw' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                  stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-share">
                  <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"></path>
                  <polyline points="16 6 12 2 8 6"></polyline>
                  <line x1="12" y1="2" x2="12" y2="15"></line>
                </svg>
                Withdraw
              </a>
            </li>
          </ul>
          {% endif %}
          
          {% if user.is_authenticated %}
          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Return History</span>
          </h6>
          <ul class="nav flex-column mb-2">
			<li class="nav-item">
			  <a class="nav-link" href="{% url 'services:transactionHistory' %}">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
				  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
				  class="feather feather-layers">
				  <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
				  <polyline points="2 17 12 22 22 17"></polyline>
				  <polyline points="2 12 12 17 22 12"></polyline>
				</svg>
				Transaction History
			  </a>
		</li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'services:report' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-bar-chart-2">
                  <line x1="18" y1="20" x2="18" y2="10"></line>
                  <line x1="12" y1="20" x2="12" y2="4"></line>
                  <line x1="6" y1="20" x2="6" y2="14"></line>
                </svg>
                Daily
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'services:monthlyReport' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                    class="feather feather-bar-chart-2">
                    <line x1="18" y1="20" x2="18" y2="10"></line>
                    <line x1="12" y1="20" x2="12" y2="4"></line>
                    <line x1="6" y1="20" x2="6" y2="14"></line>
                </svg>
                Monthly
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'services:yearlyReport' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                    class="feather feather-bar-chart-2">
                    <line x1="18" y1="20" x2="18" y2="10"></line>
                    <line x1="12" y1="20" x2="12" y2="4"></line>
                    <line x1="6" y1="20" x2="6" y2="14"></line>
                </svg>
                Yearly
              </a>
            </li>
          </ul>
          
          {% endif %}
        </div>
      </nav>

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          {% block body_block %}
          {% endblock %}
      </main>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://getbootstrap.com/docs/4.3/assets/js/vendor/jquery-slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
  {% block js_block %}
  {% endblock %}
</body>

</html>

nusFinTech/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
    {% block body_block %}
	<div class="row-fluid">
		<div class="h-100 w-100 text-center">
		<h1>Welcome to DBS SaVest</h1>
		<canvas class="my-4 w-100 chartjs-render-monitor" id="myChart" width="1076" height="454"
            style="display: block; width: 1076px; height: 454px;"></canvas>

		</div>
	</div>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
        
        <script>
            /* globals Chart:false, feather:false */

            (function () {
                'use strict'

                feather.replace()

                // Graphs
                var ctx = document.getElementById('myChart')
                // eslint-disable-next-line no-unused-vars
                var myChart = new Chart(ctx, {
                    type: 'doughnut',
                    data: {
                        labels: ['Equity (%)', 'Fixed Income (%)', 'Commodity (%)', 'Cash (%)'],
                        datasets: [{
							data: [{{ etf_history.equity_pct }}, {{ etf_history.fixed_income_pct }}, {{ etf_history.commodities_pct }}, {{ etf_history.cash_pct }}],
							backgroundColor: [ '#ff6384', '#36a2eb', '#cc65fe', '#ffce56'],
                    	}
						],
						
					
                    },
                    options: {
						responsive: true,
						legend: {
							position: 'top',
						},
						title: {
							display: true,
							text: 'Latest AUM Composition ({{ etf_history.date|date:"d/m/Y"}})'
						},
						animation: {
							animateScale: true,
							animateRotate: true
						}
					}
                })
            }())

        </script>
    {% endblock %}

nusFinTech/templates/layout.html
<!DOCTYPE html>
{% load staticfiles %}
<!-- saved from url=(0054)# -->
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v3.8.5">
  <title>NUS Fund Management System</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/dashboard/">

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="{% static "css/layout.css" %}" rel="stylesheet">
  <style type="text/css">
    /* Chart.js */
    @-webkit-keyframes chartjs-render-animation {
      from {
        opacity: 0.99
      }

      to {
        opacity: 1
      }
    }

    @keyframes chartjs-render-animation {
      from {
        opacity: 0.99
      }

      to {
        opacity: 1
      }
    }

    .chartjs-render-monitor {
      -webkit-animation: chartjs-render-animation 0.001s;
      animation: chartjs-render-animation 0.001s;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">NUS Micro FinTech</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <a class="nav-link" href="#">Sign out</a>
      </li>
    </ul>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-home">
                  <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                  <polyline points="9 22 9 12 15 12 15 22"></polyline>
                </svg>
                Dashboard <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-users">
                  <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                  <circle cx="9" cy="7" r="4"></circle>
                  <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                  <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                </svg>
                Account
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-bar-chart-2">
                  <line x1="18" y1="20" x2="18" y2="10"></line>
                  <line x1="12" y1="20" x2="12" y2="4"></line>
                  <line x1="6" y1="20" x2="6" y2="14"></line>
                </svg>
                Reports
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-layers">
                  <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
                  <polyline points="2 17 12 22 22 17"></polyline>
                  <polyline points="2 12 12 17 22 12"></polyline>
                </svg>
                Settings
              </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'services:makeTransaction' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                    class="feather feather-layers">
                    <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
                    <polyline points="2 17 12 22 22 17"></polyline>
                    <polyline points="2 12 12 17 22 12"></polyline>
                  </svg>
                  Make Transaction
                </a>
              </li>
          </ul>

          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Saved reports</span>
            <a class="d-flex align-items-center text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-plus-circle">
                <circle cx="12" cy="12" r="10"></circle>
                <line x1="12" y1="8" x2="12" y2="16"></line>
                <line x1="8" y1="12" x2="16" y2="12"></line>
              </svg>
            </a>
          </h6>
          <ul class="nav flex-column mb-2">
            <li class="nav-item">
              <a class="nav-link" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-file-text">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                  <polyline points="14 2 14 8 20 8"></polyline>
                  <line x1="16" y1="13" x2="8" y2="13"></line>
                  <line x1="16" y1="17" x2="8" y2="17"></line>
                  <polyline points="10 9 9 9 8 9"></polyline>
                </svg>
                Monthly
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-file-text">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                  <polyline points="14 2 14 8 20 8"></polyline>
                  <line x1="16" y1="13" x2="8" y2="13"></line>
                  <line x1="16" y1="17" x2="8" y2="17"></line>
                  <polyline points="10 9 9 9 8 9"></polyline>
                </svg>
                Quarterly
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                  stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                  class="feather feather-file-text">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                  <polyline points="14 2 14 8 20 8"></polyline>
                  <line x1="16" y1="13" x2="8" y2="13"></line>
                  <line x1="16" y1="17" x2="8" y2="17"></line>
                  <polyline points="10 9 9 9 8 9"></polyline>
                </svg>
                Yearly
              </a>
            </li>
          </ul>
        </div>
      </nav>

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          {{insert_here}}
      </main>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://getbootstrap.com/docs/4.3/assets/js/vendor/jquery-slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
  
</body>

</html>

nusFinTech/templates/login.html
{% extends "base.html" %}
    {% block body_block %}
        <form action="{% url 'user_login' %}" method="POST"><br>
            <label for="username">Username</label>
            <input type="text" name="username" placeholder="Enter username"/>
            <br/>
            <label for="password">Password</label>
            <input type="password" name="password"/>
            <br/>
            {% csrf_token %}
            <input type="submit" name="submit" value="Login"/> 
        </form>
    {% endblock %}

nusFinTech/templates/register.html
<!DOCTYPE html>
{% extends "base.html" %}
    {% block body_block %}
    {% if registered %}
        <h1>Thank you for resistration!</h1>
    {% else %}
        <form method="POST">
            {{ user_form.as_p }}
            {{ account_form.as_p }}
            {% csrf_token %}
            <input type="submit" name="submit" value="Submit"/> 
        </form>
    {% endif %}
    {% endblock %}